import os

IS_PROD = os.environ["IS_PROD"]

# Kafka File Notifications
FILE_NOTIFICATION_TOPIC_NAME = os.environ["FILE_NOTIFICATION_TOPIC_NAME"]
KAFKA_BOOTSTRAP_SERVERS = os.environ["KAFKA_BOOTSTRAP_SERVERS"]
KAFKA_GROUP_ID = os.environ["KAFKA_GROUP_ID"]

# End of Readout
END_READOUT_LISTENER_ENABLED = os.environ.get("SHOULD_RUN_END_READOUT_LISTENER")
if END_READOUT_LISTENER_ENABLED:
    END_READOUT_TOPIC_NAME = os.environ["END_READOUT_TOPIC_NAME"]
    SASL_USERNAME = os.environ["SASL_USERNAME"]
    SASL_PASSWORD = os.environ["SASL_PASSWORD"]
    SASL_MECHANISM = os.environ["SASL_MECHANISM"]

    SECURITY_PROTOCOL = os.environ["SECURITY_PROTOCOL"]

PERSISTENCE_ENABLED = os.environ.get("PERSISTENCE_ENABLED")
if PERSISTENCE_ENABLED:
    POSTGRES_CONNECTION_STRING = os.environ["POSTGRES_CONNECTION_STRING"]

# S3 access
S3_ENDPOINT_URL = os.environ.get("S3_ENDPOINT_URL")
AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
EXPECTED_SENSORS_FILENAME = os.environ["EXPECTED_SENSORS_FILENAME"]
STORAGE_BUCKET_NAME = os.environ["STORAGE_BUCKET_NAME"]

MAX_LATE_FILE_TIME = os.environ.get("MAX_FILE_LATE_TIME", 15)
NOTIFICATION_CLEANUP_INTERVAL = os.environ.get("NOTIFICATION_CLEANUP_INTERVAL", 5)
