import os


FILE_NOTIFICATION_TOPIC_NAME = os.environ["FILE_NOTIFICATION_TOPIC_NAME"]
END_READOUT_TOPIC_NAME = os.environ["END_READOUT_TOPIC_NAME"]

SASL_USERNAME = os.environ["SASL_USERNAME"]
SASL_PASSWORD = os.environ["SASL_PASSWORD"]
SASL_MECHANISM = os.environ["SASL_MECHANISM"]
SECURITY_PROTOCOL = os.environ["SECURITY_PROTOCOL"]

POSTGRES_CONNECTION_STRING = os.environ["POSTGRES_CONNECTION_STRING"]
AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]

EXPECTED_SENSORS_FILENAME = os.environ["EXPECTED_SENSORS_FILENAME"]
STORAGE_BUCKET_NAME = os.environ["STORAGE_BUCKET_NAME"]

MAX_LATE_FILE_TIME = os.environ.get("MAX_FILE_LATE_TIME", 15)
NOTIFICATION_CLEANUP_INTERVAL = os.environ.get("NOTIFICATION_CLEANUP_INTERVAL", 15)
